# Generated by Django 4.2.25 on 2025-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('member_count', models.IntegerField(default=0)),
                ('max_member', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=30)),
                ('sports_type', models.CharField(choices=[('futsal', 'Futsal'), ('bulutangkis', 'Bulutangkis'), ('basket', 'Basket')], default='futsal', max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('community_image', models.ImageField(blank=True, null=True, upload_to='community_images/')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
