# Generated by Django 5.2.6 on 2025-10-13 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lapangan', models.CharField(max_length=100, unique=True)),
                ('jenis_olahraga', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=100)),
                ('harga_per_jam', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fasilitas', models.TextField(default='-')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('jumlah_ulasan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SlotTersedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_akhir', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.lapangan')),
            ],
            options={
                'unique_together': {('lapangan', 'tanggal', 'jam_mulai')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_booking', models.DateTimeField(auto_now_add=True)),
                ('total_bayar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status_pembayaran', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Sudah Dibayar'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.slottersedia')),
            ],
        ),
    ]
