# Generated by Django 5.2.6 on 2025-10-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbooking', '0002_alter_profile_role'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='pengelola',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lapangan_dikelola', to='authbooking.profile'),
        ),
    ]
