# Generated by Django 5.2.6 on 2025-10-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbooking', '0003_alter_profile_role'),
        ('booking', '0002_lapangan_pengelola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='pengelola',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PEMILIK'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lapangan_dikelola', to='authbooking.profile'),
        ),
    ]
