# Generated by Django 5.2.6 on 2025-10-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_lapangan_pengelola'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottersedia',
            name='pending_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_reserved_by_pending', to='booking.booking'),
        ),
    ]
