# Generated by Django 5.2.5 on 2025-10-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_lapangan_deskripsi_lapangan_foto_utama_and_more'),
        ('booking', '0004_slottersedia_pending_booking'),
    ]

    operations = [
    ]
