# Generated by Django 5.2.5 on 2025-10-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_20251023_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapangan',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='lapangan',
            name='foto_utama',
        ),
        migrations.RemoveField(
            model_name='lapangan',
            name='is_active',
        ),
    ]
