# Generated by Django 5.2.5 on 2025-10-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_lapangan_deskripsi_remove_lapangan_foto_utama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lapangan',
            name='foto_utama',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan/'),
        ),
        migrations.AddField(
            model_name='lapangan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
