# Generated by Django 4.2.25 on 2025-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_lapangan_deskripsi_lapangan_foto_utama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan_photos/'),
        ),
        migrations.AddField(
            model_name='lapangan',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan_photos/'),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='foto_utama',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan_photos/'),
        ),
    ]
