# Generated by Django 4.2.25 on 2025-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_lapangan_foto_2_lapangan_foto_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan/'),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan/'),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='foto_utama',
            field=models.ImageField(blank=True, null=True, upload_to='lapangan/'),
        ),
    ]
