# Generated by Django 5.2.6 on 2025-10-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authbooking', '0002_alter_profile_role'),
        ('booking', '0002_lapangan_pengelola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.lapangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authbooking.profile')),
            ],
        ),
    ]
