# Generated by Django 5.2.6 on 2025-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User (Penyewa)'), ('ADMIN', 'Admin (Pemilik Lapangan)')], default='USER', max_length=5),
        ),
    ]
