# Generated by Django 5.2.6 on 2025-10-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbooking', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PENYEWA', 'Penyewa Lapangan'), ('PEMILIK', 'Pemilik Lapangan')], default='PENYEWA', max_length=7),
        ),
    ]
