# Generated by Django 5.2.6 on 2025-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbooking', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nomor_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
